services:
  mysql:
    image: mysql:lts
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=${ROOT_PASSWORD}
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PWD}
    ports:
      - 3306:3306
    volumes:
     - mysql-data:/var/lib/mysql
    container_name: mysql
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 10s
      timeout: 5s
      retries: 5
  phpmyadmin:
    image: phpmyadmin
    environment:
      - PMA_HOST=mysql
    ports:
      - 8080:80
    depends_on:
     - "mysql"
    container_name: phpmyadmin
  my-ex7-app:
    depends_on:
      mysql:
        condition: service_healthy    
    image: ${NEXUS_REPO}:8083/my-ex7-app:1.1
    ports:
      - 8083:8080
    environment:
      - DB_USER=${DB_USER}
      - DB_PWD=${DB_PWD}
      - DB_SERVER=${DB_SERVER}
      - DB_NAME=${DB_NAME}
    container_name: my-ex7-app
volumes:
  mysql-data:
    driver: local
